name: Update Download Stats

on:
  schedule:
  - cron: '30 20 * * *'

jobs:
  checkLatestStatistics:
    name: Check latest statistics
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check latest statistics
      uses: ./
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
